mgmt_interface: Management1
mgmt_interface_vrf: MGMT
mgmt_gateway: 172.16.100.1
mgmt_destination_networks:
  - 0.0.0.0/0

## disabled due to a bug
## try if you need a challenge =)
eos_cli: |
  management security
   ssl profile eAPI
      cipher-list HIGH:!eNULL:!aNULL:!MD5:!ADH:!ANULL
      certificate eAPI.crt key eAPI.key
  !
  interface Management1
      no lldp receive
      no lldp transmit
  !
  management api http-commands
   protocol https ssl profile eAPI
   no shutdown
   !
   vrf MGMT
      no shutdown
  !
  platform tfa personality arfa
  !
  event-handler ConfigureHardwareModel
    trigger on-boot
    action bash
       python -m Acons Sysdb << EOF
       cd /ar/Sysdb/hardware/entmib
       if (model := os.getenv('MODEL_NAME')):
          _.fixedSystem.modelName = model
       elif (model := os.getenv('CHASSIS_MODEL_NAME')):
          _.chassis = (1,0,'Chassis')
          _.chassis.modelName = model
          for var, value in os.environ.items():
             if var.startswith('CHASSIS'):
                keys = var.split('_')
                if keys[1] == "SUPERVISOR":
                   i = int(keys[2])
                   _.chassis.cardSlot.newMember(100002000+i, i, 'Supervisor')
                   _.chassis.cardSlot[i].card = (100002100+i, i, 'Supervisor')
                   _.chassis.cardSlot[i].card.modelName = value
                elif keys[1] == "LINECARD":
                   i = int(keys[2]) + 2
                   _.chassis.cardSlot.newMember(100002000+i, i, 'Linecard')
                   _.chassis.cardSlot[i].card = (100002100+i, i, 'Linecard')
                   _.chassis.cardSlot[i].card.modelName = value

       EOF
