---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# Common AVD group variables
fabric_name: FABRIC

# Generate CSVs with fabric link info.
eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

# Define underlay and overlay routing protocol to be used
#underlay_routing_protocol: ospf-ldp
#underlay_routing_protocol: isis-ldp
#underlay_routing_protocol: isis-sr
underlay_routing_protocol: isis-sr-ldp
overlay_routing_protocol: ibgp

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$QJUtFkyu9yoecsq.$ysGzlb2YXaIMvezqGEna7RE8CMALJHnv7Q1i.27VygyKUtSeX.n2xRTyOtCR8eOAl.4imBLyhXFc4o97P5n071
  - name: admin
    privilege: 15
    role: network-admin
    # Password set to "admin". 
    sha512_password: $6$1vIyi/MdhdHtK4zg$9AON0mlzmK29KIuRgRGBKlutM4zEvXqt07qohoxdVXeGDH1aTu7uRUf/gmbGwAVvI7DwlPfWBF374av3djqUI0 
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPh1fn/zh7sMvIo0AMcnQ888HrNU79trbb8Jks8feXoP ubuntu@LHVS0020"

# AAA Authorization Settings
aaa_authorization:
  exec:
    default: local

name_servers:
  - 8.8.8.8
  - 8.8.4.4

ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
    - name: time.google.com
      vrf: MGMT

dns_domain: angacom.lab

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  mpls_overlay_peers:
    password: $1c$G8BQN0ezkiJOX2cuAYpsEA==
  rr_overlay_peers:
    password: $1c$G8BQN0ezkiJOX2cuAYpsEA==

management_eapi:
  enable_https: true

management_api_http:
  enable_https: true
  https_ssl_profile: eAPI
  enable_vrfs:
    - name: MGMT
  protocol_https_certificate:
    certificate: eAPI.crt
    private_key: eAPI.key

management_security:
  password:
    encryption_key_common: true

daemon_terminattr:
  cvaddrs:
    - "apiserver.arista.io:443"
  cvauth:
    method: token-secure
    token_file: "/mnt/flash/cv-onboarding-token"
  cvvrf: MGMT
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  disable_aaa: True
